name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'  # Runs daily at 4:30 AM UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # VERY IMPORTANT

      - name: Daily Commit by 24f1001831@ds.study.iitm.ac.in
        run: |
          echo "$(date)" >> log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Daily update"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
